# Generated by Django 6.0.4 on 2026-05-01 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_text', models.CharField(max_length=255, verbose_name='Текст оповіщення')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активувати тривогу')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Статус небезпеки',
                'verbose_name_plural': 'Статуси небезпеки',
            },
        ),
    ]
