# Generated by Django 6.0.4 on 2026-05-01 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0002_emergencystatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='check_in',
            field=models.DateTimeField(verbose_name='Заїзд'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out',
            field=models.DateTimeField(verbose_name='Виїзд'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='guest_name',
            field=models.CharField(max_length=255, verbose_name="Ім'я гостя"),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managment.room', verbose_name='Кімната'),
        ),
        migrations.AlterField(
            model_name='room',
            name='is_occupied',
            field=models.BooleanField(default=False, verbose_name='Зайнята'),
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.CharField(max_length=10, unique=True, verbose_name='Номер приміщення'),
        ),
    ]
