# Generated by Django 6.0.4 on 2026-05-01 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0003_alter_booking_check_in_alter_booking_check_out_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.CharField(max_length=10, verbose_name='Номер приміщення'),
        ),
    ]
