# Generated by Django 6.0.4 on 2026-05-01 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0004_alter_room_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='managment.room', verbose_name='Кімната'),
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.CharField(max_length=10, unique=True, verbose_name='Номер приміщення'),
        ),
    ]
