# Generated by Django 6.0.4 on 2026-05-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0005_visitor_room_alter_room_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='is_occupied',
            field=models.BooleanField(default=False, verbose_name='Зайнята (старе поле)'),
        ),
    ]
