# Generated by Django 6.0.4 on 2026-05-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0007_alter_room_is_occupied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='is_occupied',
            field=models.BooleanField(default=False, verbose_name='Ручне керування (запасне)'),
        ),
    ]
