# Generated by Django 6.0.4 on 2026-05-01 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0010_alter_room_is_occupied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencystatus',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активність'),
        ),
        migrations.AlterField(
            model_name='room',
            name='is_occupied',
            field=models.BooleanField(default=False, verbose_name='Технічний статус'),
        ),
    ]
